### ISSUE TITLE
use_circle_deploy() throws 404 Not Found

### ISSUE THREAD

**Issue by jdblischak** [ropenscilabs/circle#8]
I was able to create a token using `browse_circle_token()` and `edit_circle_config()`. Then I activated CircleCI with `enable_repo()`.

GitHub repo: https://github.com/jdblischak/test-circle
CircleCI project: https://circleci.com/gh/jdblischak/test-circle

Thus I assume I have the CircleCI authentication configured properly.

When I try to run `use_circle_deploy()`, it fails with a 404 error:

```
use_circle_deploy()
x No 'github-user-key' found.
Error in create_checkout_key(user = user, repo = repo, type = "user-key") : 
  Not Found (HTTP 404). Failed to creating checkout keys for repo jdblischak/test-circle on Circle CI.
```

Maybe this is an issue with the scopes I have enabled for my GitHub PAT?

```
gh::gh_whoami()$scopes
[1] "public_repo, read:org, repo:status"
```

<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] circle_0.5.0.9001

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         clisymbols_1.2.0   fansi_0.4.1        rprojroot_1.2      packrat_0.5.0      crayon_1.3.4      
 [7] assertthat_0.2.1   R6_2.4.1           backports_1.1.5    jsonlite_1.6       git2r_0.26.1.9000  httr_1.4.1        
[13] rlang_0.4.4        cli_2.0.1          curl_4.2           rstudioapi_0.10    fs_1.3.1.9000      gh_1.1.0          
[19] tools_3.6.2        glue_1.3.1         compiler_3.6.2     usethis_1.5.1.9000
```
</details>

**Comment by pat-s** [comment]
- Did you install the Circle CI Github app as mentioned [here](https://docs.ropensci.org/circle/articles/circle.html#authentication)?

- Is your repo listed when browsing `browse_circleci()`?

**Comment by jdblischak** [comment]
> Did you install the Circle CI Github app as mentioned here?

Since I've been using CircleCI with GitHub, I assumed that I already had the app installed. When I went to the [app in the Marketplace](https://github.com/marketplace/circleci), it said that I had already granted it access:

![image](https://user-images.githubusercontent.com/1608317/73803111-cb00a780-478d-11ea-932d-81303be42c18.png)

The next thing I tried was specifying the "Free" plan. I got this notice as I was confirming that I wanted the "Free" plan.

![image](https://user-images.githubusercontent.com/1608317/73803254-321e5c00-478e-11ea-88e1-c78c81b66c0f.png)

Now it shows that in addition to granting it access, I've also selected a plan:

![image](https://user-images.githubusercontent.com/1608317/73803549-15ceef00-478f-11ea-8510-c4b6006c80a1.png)

However, I still get the 404 error.

> Is your repo listed when browsing `browse_circleci()`?

I can't use the function `usethis::browse_circleci()` because the test repo I set up isn't an R package. However, doesn't that function take you to the CircleCI project page for the GitHub repository? I confirmed above that `enable_repo()` produced a Circle CI project. Here's the link:

https://circleci.com/gh/jdblischak/test-circle

Using `circle::list_projects()`, I can see my test repo and all my other repos that I use with Circle CI.

```
library(circle)
response <- list_projects()
content <- response[["content"]]
repos <- sapply(content, function(x) x[["reponame"]])
length(repos)
## [1] 17
repos[length(repos)]
## [1] "test-circle"
```

**Comment by pat-s** [comment]
- Have you set your API token via env var `R_CIRLCLE`?

I've added some more context to the "deployment" section of the [vignette](https://docs.ropensci.org/circle/articles/circle.html#deployment). I hope that makes things more clear.

As per your comment on Twitter:

> Could you please point me to the Circle CI docs that explain the new way of doing it? I am following the instructions below, which add a key to the repository: 

There is no section where Circle explains what happens behind the scenes when a "user-key" is created via their web interface. They explain only the long (and tedious) manual way of creating a SSH key pair.
It could be that their docs are not up-to-date.
In the end its just a short cut to create a SSH key pair with "write" permissions to your repo.

**Comment by jdblischak** [comment]
> Have you set your API token via env var R_CIRLCLE?

I had been using `.circle/cli.yml`. Today I tried with `R_CIRCLE`, but the result was the same.

> There is no section where Circle explains what happens behind the scenes when a "user-key" is created via their web interface.

While it's not in the docs, it is documented in the settings page that you mention in the updated vignette (the "Checkout SSH Keys" section of the Settings, `https://circleci.com/gh/<account>/<repo>/edit#checkout`).

Based on that documentation, I think my original theory was correct. My GitHub PAT doesn't have the scope `admin:public_key`, and hence the 404 error.

> In order to do so, you'll need to grant authorization from GitHub to the "admin:public_key" scope. This will allow us to add a new authorized public key to your GitHub account.

I also now better understand the key created by `use_circle_deploy()`:

> A user key is a user-specific SSH key. GitHub has the public key, and we store the private key. Possession of the private key gives the ability to act as that user, for purposes of 'git' access to projects.

I don't want to create a key that has access to my account. They specifically say that is useful if you need to access multiple private repositories. Since I only need Circle CI to have permission to access one GitHub repo, I'd prefer to only give it access to that one (and not my entire account).

**Comment by pat-s** [comment]
> I don't want to create a key that has access to my account. They specifically say that is useful if you need to access multiple private repositories. Since I only need Circle CI to have permission to access one GitHub repo, I'd prefer to only give it access to that one (and not my entire account).

I see. 
I understand your point here. However, especially when it comes to quick setup of deployment for multiple repos this is a great functionality.
I do not really see any security risks right now and I think I will leave this as the default.

---

I should make the permissions more clear probably, in the help page and in the vignette.

It is of course always possible to go the "single repo SSH key pair" way as you prefer to.
This is also how we do it on Travis CI via `travis::use_travis_deploy()`.
However there, no other way is possible.

I am open to extend `use_circle_deploy()` to also support your way and act similar to `travis::use_travis_deploy()`. However, I am not really motivated to do this on my side right now as I am happy with the current way.
PR's welcome though 😄 

Thanks for debugging with me! I also learned more details about all of this now and how to prevent further users from going down that route.

---

I still do not understand though why `use_circle_deploy()` results in a 404 if the API key is set and the Github app is installed.
It should trigger the same action as clicking on the "add user key" button.
If you have access to the Circle CI API via your API key, this should work.
The GITHUB_PAT should not have any relation here since we only use this to scrape the repo information but not for the Circle CI API call.

I'd really appreciate if you could help me tracking this down as this seems like a thing that could happen more often.
As always when working with APIs its hard to restart with a vanilla setup once an account is configured.

**Comment by jdblischak** [comment]
> I am open to extend use_circle_deploy() to also support your way and act similar to travis::use_travis_deploy(). However, I am not really motivated to do this on my side right now as I am happy with the current way.
PR's welcome though 

No need to change it. I was just trying to understand what it was doing.

> Thanks for debugging with me! I also learned more details about all of this now and how to prevent further users from going down that route.

Of course! I learned a lot from our discussion as well. I updated my blog post in https://github.com/jdblischak/blog.jdblischak.com/commit/d28efe05fd251f698547fe30ac3d19c6254e9355 to reflect my improved understanding.

> I'd really appreciate if you could help me tracking this down as this seems like a thing that could happen more often.

Sure. What would you like me to try?

**Comment by jdblischak** [comment]
When I click on the "Authorize GitHub" button to create a user key, I get the following request to grant the CircleCI app permission to add public SSH keys:

![image](https://user-images.githubusercontent.com/1608317/73856654-c971c680-4803-11ea-9a8a-bc40c07898a6.png)

So maybe you can only programmatically use this API endpoint of the CircleCI app once you've authorized this functionality with GitHub.

**Comment by pat-s** [comment]
> So maybe you can only programmatically use this API endpoint of the CircleCI app once you've authorized this functionality with GitHub.

That's probably it, yes.

For me I have

- Full control of user public keys
- Full control of private repositories
- Access user email addresses (read-only)

Interesting. So with this, I think we can close here. I'll add a few sentences about this to the auth section in the README.

Personally, I still do not mind giving access to the SSH keys and therefore will stick to it as a default for the package. But I understand that not everyone wants this.

Thanks John for your help here!
